name: Mirror pre-requisite images for Shipwright samples

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:  # Manual trigger

jobs:
  mirror-images:
    if: ${{ github.repository == 'shipwright-io/build' }}
    runs-on: ubuntu-latest

    steps:
      - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e

      - name: Mirror images
        env:
          REPO: ghcr.io/${{ github.repository_owner }}/shipwright-samples
        run: |
          for IMAGE in \
            library/golang:1.23 \
            library/golang:1.24 \
            library/maven:3-jdk-8-openj9 \
            library/node:20 \
            library/node:22 \
            library/node:24 \
            library/python:3.9 \
            library/python:3.10 \
            library/python:3.11 \
            library/python:3.12 \
            library/python:3.13 \
            openliberty/open-liberty:kernel-java8-openj9-ubi \
            ; do
            crane cp "${IMAGE}" "${REPO}/$(cut -d/ -f2 <<<"${IMAGE}")"
          done
